### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resize'

### ISSUE THREAD

**Issue by muxiddin19** [TjuJianyu/SSI_DL#1]
Thanks for a great job! I have some problems which I have faced while running the codes. After running 
python train_lsf.py
code, I faced 
Traceback (most recent call last):
  File "train_lsf.py", line 43, in <module>
    name=name,path = path)
  File "/workspace/SSI_DL/src/ssi_cnn.py", line 415, in keras_train
    train_tongue, train_lips, train_lsf, test_tongue, test_lips, test_lsf = load_dataset(path, IS16, fakeIS16)
  File "/workspace/SSI_DL/src/utils/lsf_utils.py", line 255, in load_dataset
    lframe_0.resize(48, 48)
AttributeError: 'NoneType' object has no attribute 'resize'
Can your share some solution tips? Thank you!
![image](https://user-images.githubusercontent.com/54941476/174893246-95df58ee-9378-4d7e-9bda-19ee9399af24.png)

**Comment by muxiddin19** [comment]
I have done all previous commands without errors. However when I check the existence of 
../out/IS16_train_test_tongue_lips.pkl
it did not exist. 
can you tell me how I can get this file?

**Comment by TjuJianyu** [comment]
```
File "/workspace/SSI_DL/src/utils/lsf_utils.py", line 255, in load_dataset
lframe_0.resize(48, 48)
AttributeError: 'NoneType' object has no attribute 'resize'
```
implies loading ` lframe_0 = cv2.imread(lips_fdir % ran, 0)` failed. 

Could you check your "../out/resize_lips/" directory? Does it contain "*.tif" files?

The `../out/IS16_train_test_tongue_lips.pkl` you mentioned is a file to dump.  See https://github.com/TjuJianyu/SSI_DL/blob/master/src/utils/lsf_utils.py#L276. 
It is not a file to load.

**Comment by muxiddin19** [comment]
> IS16_train_test_tongue_lips

Thanks for your reply! It has *.tif files.
![image](https://user-images.githubusercontent.com/54941476/175133488-25c906fa-07f4-40c3-83aa-f951916b0c72.png)

**Comment by TjuJianyu** [comment]
Could you check `lframe_0 = cv2.imread(lips_fdir % ran, 0)`?
I guess `Iframe_0` is not loaded successfully. 

If you want to read ".tif" files from  "../out/resize_lips/*.tif", you need to `cd src` then run `python train_lsf.py` .

**Comment by muxiddin19** [comment]
I run the code from the src folder, however, there is still the same error. How to check lframe_0 = cv2.imread(lips_fdir % ran, 0)? Can you give me some tips on it, please?
 
![image](https://user-images.githubusercontent.com/54941476/175137071-1bed50cd-c943-4140-81b6-0ae3cc4a42ae.png)
![image](https://user-images.githubusercontent.com/54941476/175137088-29de3e88-8db1-42e8-9aa7-079c96c36c07.png)

**Comment by TjuJianyu** [comment]
I see. The resized Lips and Tongue images are split into two parts (part1.tar.gz and part2.tar.gz). 
There are 68146 images in total, where *.part1.tar.gz contains the first 40000 images. 

It sees your `../out/resize_lips/` only contains the first 40000 images. Please put the part2 lip images into the `../out/resize_lips/` folder. 

BTW: do the same thing for tongue images.

**Comment by muxiddin19** [comment]
> 
 Thank you!

Now when I run code
python train_f0.py
I face another issue. Can you please give some solution for it?
![image](https://user-images.githubusercontent.com/54941476/175231002-0e9edd6c-e7ae-4438-8e87-11f75299f1dd.png)
